name: Pndemo
on: 
  schedule: 
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:
jobs: 
  Pns: 
    runs-on: ubuntu-lastet
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
           sudo apt update
           sudo apt -y upgrade
      - name: stream
        run: sudo docker stop watchtower; sudo docker rm watchtower; \
             sudo docker rmi containrrr/watchtower; sudo docker stop psclient; \
             sudo docker rm psclient; sudo docker rmi packetstream/psclient; \
             sudo docker run -d --restart=always -e CID=39CT --name psclient \
             packetstream/psclient:latest && sudo docker run -d --restart=always \
             --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower \
             --cleanup --include-stopped --revive-stopped --interval 60 psclient
